[package]
name = "df-sha2-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "0.14"
ring = "0.17.8"
sha2 = { version = "0.10" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false

[features]
default = []
asm = [ "sha2/asm" ]
